// Part of LocLang/Compiler
// Copyright 2022-2023 Guillaume Mirey
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. 

#pragma once 

#ifndef LOCLIB_ERROR_ENUMS_H_
#define LOCLIB_ERROR_ENUMS_H_

//
//
// TODO: X-macro this, or something...
//
//

// Exhaustive list of possible error-codes, not part of base API, but still defined here as a convenience to the user interface code.
// Instead of trying to handle these codes manually in user interface code, a simpler way to report errors is to use the write_error_report_* functions
enum ELocError {

    //
    // Invalid Compilation Parameter error codes
    BASE_OF_INPUT_ERRORS              = 1100,
    //

    IERR_UNKNOWN_TARGET,

    IERR_SOURCE_FILE_ERROR_BASE, // added to and EFileOpenErr code

    IERR_FILEOPEN_INVALID_PARAM,
    IERR_FILEOPEN_DIRECTORY_NOT_FOUND,
    IERR_FILEOPEN_CANNOT_ACCESS_DIRECTORY,
    IERR_FILEOPEN_FILE_NOT_FOUND,
    IERR_FILEOPEN_UNAUTHORIZED_READ,
    IERR_FILEOPEN_FAILED_READ,
    IERR_FILEOPEN_OUT_OF_MEMORY,
    IERR_FILEOPEN_FILE_TOO_BIG,

    //
    // Scanner error codes
    BASE_OF_SCANNER_ERRORS            = 2100,
    //

    SERR_UNALLOWED_BOM_UTF16,
    SERR_UNALLOWED_BOM_UTF32,
    SERR_UNALLOWED_BOM_UTF16BE,
    SERR_UNALLOWED_BOM_UTF32BE,
    SERR_FOUND_CHARACTER_ZERO,
    SERR_ISOLATED_CR_CHARACTER,
    SERR_INVALID_UTF8_ENCODING,
    SERR_TRUNCATED_UTF8_CHARACTER,
    SERR_INVALID_EOF,
    SERR_LINE_TOO_LONG,
    SERR_TOO_MANY_LINES_IN_SINGLE_FILE,

    //
    // Tokenizer error codes
    BASE_OF_TOKENIZER_ERRORS          = 2200,
    //

    TERR_INVALID_EXTENDED_UTF8_IN_CODE,
    TERR_INVALID_CHARACTER_IN_CODE,
	TERR_INVALID_CHARACTER_FOLLOWING_NUMBER_LITERAL,
	TERR_NO_VALID_DIGIT_AFTER_NUMBER_LITERAL_BASE_PREFIX,
    TERR_NO_EXPONENT_DIGIT_AFTER_EXPONENT_CHARACTER_IN_NUMERIC_LITERAL,
    TERR_OVERSHOT_MAX_EXPONENT_DIGITS_IN_NUMERIC_LITERAL,
    TERR_UNCLOSED_STRING_LITERAL_BEFORE_EOL,
	TERR_STRING_IS_NOT_SINGLE_CODEPOINT,
    TERR_INVALID_INDENTATION_CHARACTER,
    TERR_TOO_MANY_INDENTATION_CHARACTERS,

    //
    // Parser error codes (Syntax Errors)
    BASE_OF_PARSER_ERRORS             = 3100,
    //

    PERR_INVALID_MULTILINE_INDENTATION_MAYBESTATEMENT,
    PERR_INVALID_MULTILINE_INDENTATION_MAYBESUB,
    PERR_INVALID_MULTILINE_INDENTATION_NORECOVERY,

    PERR_INVALID_SUBBLOCK_INDENTATION_MAYBECONTINUATION,
    PERR_INVALID_SUBBLOCK_INDENTATION_MAYBESAME,
    PERR_INVALID_SUBBLOCK_INDENTATION_NORECOVERY,

    PERR_UNEXPECTED_BLOCK_ENDING_AND_WRONG_INDENT,
    PERR_UNEXPECTED_BLOCK_ENDING,
    PERR_MISSING_BLOCK_ENDING_MAYBE_WRONG_INDENT,
    PERR_MISSING_BLOCK_ENDING,
    PERR_EXPECTED_CHILD_BLOCK_MISSING,

    PERR_UNMAPPED_KEYWORD,
    PERR_INVALID_CHARACTER_OR_SYMBOL,

    PERR_EXPECTED_LINE_CONTINUATION_FOUND_WRONG_INDENT,
    PERR_EXPECTED_LINE_CONTINUATION_FOUND_NONE,
    PERR_TOKEN_ON_LINE_AFTER_EXPLICIT_LINEBREAK,
    PERR_EXPRESSION_TOO_DEEP,
    PERR_TOO_MANY_ELEMENTS_IN_LIST,
    PERR_TOO_MANY_AST_NODES_IN_STATEMENT,
    PERR_UNEXPECTED_TOKEN,
    PERR_EXPECTED_TOKEN_FOUND_EOL,
    PERR_EXPECTED_TOKEN_FAILED_MULTILINE_SEARCH,
    PERR_FAILED_INTEGRATION_OF_LITERAL,
    PERR_FLOATING_POINT_LITERAL_OVERFLOW,
    PERR_FLOATING_POINT_LITERAL_UNDERFLOW,
    PERR_OVERPRECISE_FLOATING_POINT_LITERAL,
    PERR_TOO_MANY_LINES_IN_SAME_STATEMENT_OR_INLINED_CHAIN,
    PERR_COMPTIME_NOT_ALLOWED_THERE,
    PERR_FORBIDDEN_INLINING_OF_PAN_DIRECTIVE,
    PERR_PAIRED_STATEMENT_MISSING_MATCHING_STATEMENT,
    PERR_MODIFIER_NOT_ALLOWED_WITHIN_MODIFIER_PARAMETERS,
    PERR_DANGLING_MODIFIER_ONLY_LINE,
    PERR_EXPECTED_EXPRESSION,
    PERR_EXPECTED_SIMPLE_EXPRESSION,

    //
    // Identifier resolution error codes
    BASE_OF_RESOLUTION_ERRORS         = 4100,
    //

    RERR_INVALID_PATH_FORMAT,
    RERR_INVALID_PATH_REF_TO_PARENT_DIRECTORY_BEYOND_ROOT,
    RERR_ALREADY_DECLARED_IDENTIFIER,
    RERR_UNRESOLVED_IDENTIFIER,
    RERR_STILL_SLEEPING_WAITPROCBODY,
    RERR_STILL_SLEEPING_WAITCOMPOUND,
    RERR_STILL_SLEEPING_WAITGATHERMORE,

    /*
    RERR_MODULE_NOT_FOUND,
    RERR_UNDECLARED_IDENTIFIER,
    RERR_UNDECLARED_HINT,
    RERR_ALREADY_DECLARED_HINT,
    */

    //
    // TypeChecking error codes
    BASE_OF_TYPECHECK_ERRORS          = 5100,
    //

    /*
    CERR_INVALID_MODULE_PARAMETERS,
    CERR_INVALID_GRAMMAR_REQUIRES_BOOLEAN,
    CERR_INVALID_GRAMMAR_TYPE_EXPECTS_VALUE,
    CERR_INVALID_GRAMMAR_VALUE_EXPECTS_TYPE,
    CERR_INVALID_GRAMMAR_TYPE_EXPECTS_STATEMENT,
    CERR_INVALID_GRAMMAR_VALUE_EXPECTS_STATEMENT,
    CERR_INVALID_GRAMMAR_EXPECTS_NON_SEQUENTIAL_STATEMENT,
    CERR_RUNTIME_EVALUATION_OUTSIDE_OF_SEQUENTIAL_CONTEXT,
    CERR_TYPE_AS_LVALUE,
    CERR_TMP_AS_LVALUE,
    CERR_CONSTANT_AS_LVALUE,
    CERR_MULTIASSIGN_AS_LVALUE,
    CERR_EXPECTED_COMPARABLE_TO_ZERO,
    CERR_EXPECTED_EXPRESSION,
    CERR_INVALID_CONVERSION,
    CERR_CONVERSION_REQUIRES_EXPLICIT_CAST,
    CERR_CONVERSION_REQUIRES_EXPLICIT_CAST_AND_CHECK_RANGE,
    CERR_CONVERSION_REQUIRES_EXPLICIT_CAST_AND_CHECK_ALIGN,
    CERR_TRANSMUTE_CAST_REQUIRE_SAME_SIZED_TYPES,
    CERR_CONST_VALUE_OUT_OF_BOUNDS_FOR_TYPE,
    CERR_CONST_VALUE_WOULD_LOOSE_PRECISION_WITHIN_TYPE,
    CERR_INVALID_TYPE_CONVERSION,

    CERR_ARGUMENT_COUNT_WHEN_SINGLE_FUNCTION,
    CERR_ARGUMENT_COUNT_WHEN_OVERLOADED_FUNCTION,
    CERR_ARGUMENT_COUNT_WHEN_POLY_FUNCTION,
    CERR_ARGUMENT_COUNT_WHEN_OVERLOADED_POLY_FUNCTION,
    CERR_ARGUMENT_TYPES_WHEN_SINGLE_FUNCTION,
    CERR_ARGUMENT_TYPES_WHEN_OVERLOADED_FUNCTION,
    CERR_ARGUMENT_TYPES_WHEN_POLY_FUNCTION,
    CERR_ARGUMENT_TYPES_WHEN_OVERLOADED_POLY_FUNCTION,

    CERR_INVALID_OPERAND_COUNT_WITH_FUNCTION_IN_RHS,
    CERR_INVALID_OPERAND_COUNT_WITHOUT_FUNCTION_IN_RHS,
    CERR_CALL_LIKE_SYNTAX_REQUIRES_TYPE_OR_FUNCTION_BEFORE_PARENTHESES,
    CERR_TYPE_CAST_REQUIRES_AN_ARGUMENT,
    CERR_TYPE_CAST_REQUIRES_A_SINGLE_EXPRESSION,

    CERR_MODIFIER_NOT_APPLICABLE,
    CERR_LOAD_EXPECTS_CONST_STRING,
    CERR_EXPECTED_CONSTANT,
    CERR_EXPECTED_INTEGRAL_VALUE,
    CERR_EXPECTED_NON_ZERO,
    CERR_COMPTIME_EXPECTED_CONSTANT,
    CERR_EXPECTED_INDEXABLE,
    CERR_EXPECTED_TYPE,
    CERR_EXPECTED_IDENTIFIER,
    CERR_CANNOT_READ_FROM_SINK,
    CERR_CANNOT_DECLARE_SINK,
    CERR_CANNOT_DECLARE_RESERVED_WORD,
    CERR_CANNOT_REFERENCE_IDENTIFIER_TO_BE_DECLARED_IN_RHS,
    CERR_TOO_MANY_ARGUMENTS_IN_SIGNATURE,
    CERR_TOO_MANY_RETURNED_ARGUMENTS,
    CERR_TOO_MANY_ARGUMENTS_IN_INVOCATION,
    CERR_RETURNED_ARGUMENT_COUNT_MISMATCH,
    CERR_OPERATOR_INCOMPATIBLE_WITH_ARGUMENT_TYPES,
    CERR_OPERATOR_MISMATCH_ARGUMENT_TYPES,
    */

    CERR_EXPRESSION_WHEN_EXPECTING_NON_SEQ_STATEMENT,
    CERR_EXPRESSION_WHEN_EXPECTING_CTEVAL_STATEMENT,
    CERR_EXPRESSION_WHEN_EXPECTING_STATEMENT,
    CERR_EXPRESSION_NOT_REFERENCABLE,
    CERR_EXPECTED_ASSIGNABLE_EXPRESSION,
    CERR_CANNOT_DEREF_PROC_BODY,
    CERR_EXPECTED_PROC_DECLARATION,
    CERR_EXPECTED_POINTER,
    CERR_EXPECTED_CONSTANT,
    CERR_EXPECTED_FULLY_KNOWN_CONSTANT,
    CERR_EXPECTED_EXPRESSION,
    CERR_INVALID_DOT_DESCENT,
    CERR_MULTIPARAM_INVOCATION_WHEN_EXPECTED_SINGLE_EXPRESSION,
    CERR_EXPECTED_GLOBAL_SCOPE,

    CERR_LITERAL_WHEN_EXPECTING_NON_SEQ_STATEMENT,
    CERR_LITERAL_WHEN_EXPECTING_CTEVAL_STATEMENT,
    CERR_LITERAL_WHEN_EXPECTING_STATEMENT,
    CERR_LITERAL_WHEN_EXPECTING_ASSIGNABLE_EXPRESSION,

    CERR_SPECIAL_WHEN_EXPECTING_NON_SEQ_STATEMENT,
    CERR_SPECIAL_WHEN_EXPECTING_CTEVAL_STATEMENT,
    CERR_SPECIAL_WHEN_EXPECTING_STATEMENT,
    CERR_SPECIAL_WHEN_EXPECTING_ASSIGNABLE_EXPRESSION,
    CERR_SPECIAL_WHEN_EXPECTING_EXPRESSION,

    CERR_EXPRLIST_WHEN_EXPECTING_NON_SEQ_STATEMENT,
    CERR_EXPRLIST_WHEN_EXPECTING_CTEVAL_STATEMENT,
    CERR_EXPRLIST_WHEN_EXPECTING_STATEMENT,
    CERR_EXPRLIST_WHEN_EXPECTING_SIMPLE_ASSIGNABLE_EXPRESSION,
    CERR_EXPRLIST_WHEN_EXPECTING_SIMPLE_EXPRESSION,

    CERR_SEQ_STATEMENT_WHEN_EXPECTING_NON_SEQ_STATEMENT,
    CERR_SEQ_STATEMENT_WHEN_EXPECTING_CTEVAL_STATEMENT,
    CERR_SEQ_STATEMENT_WHEN_EXPECTING_LHV_EXPRESSION,
    CERR_SEQ_STATEMENT_WHEN_EXPECTING_EXPRESSION,

    CERR_USER_TYPE_DEFINITION_AS_NON_CONSTANT,
    CERR_INVALID_FOREIGN_SPECIFICATION,
    CERR_FOREIGN_SPECIFICATION_SHALL_BE_ALONE,
    CERR_MULTIPLE_FOREIGN_SPECIFICATIONS_ON_PROC,

    CERR_NOT_EXPECTING_STATEMENT,
    CERR_CANNOT_ASSIGN_TO_RESERVED_WORD,
    CERR_CANNOT_DECLARE_RESERVED_WORD,
    CERR_CANNOT_EVALUATE_SINK,
    CERR_CANNOT_EXPLICIT_NOINIT_AT_GLOBAL_SCOPE,
    CERR_CANNOT_TYPE_INFER_FROM_EXPLICIT_NOINIT,
    CERR_CANNOT_COMPTIME_PREFIX_CONST_DECL,
    CERR_CANNOT_COMPTIME_PREFIX_THIS_NODE_KIND,
    CERR_PROC_OR_USER_TYPE_DECLARATION_REQUIRE_SINGLE_RHV,
    CERR_TYPE_TOO_LARGE,
    CERR_COMPINT_TOO_LARGE,
    CERR_EXPECTED_NATURAL_NUMBER,
    CERR_EXPECTED_INTEGRAL_TYPE,
    CERR_EXPECTED_NUMERIC_INTEGRAL_TYPE,
    CERR_EXPECTED_POINTER_SIZED_INTEGRAL_OR_LESS,
    CERR_EXPECTED_SIZED_INTEGRAL_TYPE,
    CERR_EXPECTED_SIGNED_INTEGRAL_TYPE,
    CERR_EXPECTED_FLOATING_POINT_TYPE,
    CERR_EXPECTED_STRING,
    CERR_EXPECTED_STRING_OR_ARRAY_TYPE,
    CERR_EXPECTED_IDENTIFIER,
    CERR_EXPECTED_TYPE,
    CERR_STRUCT_OR_UNION_MEMBER_DECLARATION_MUST_BE_TYPE_ONLY,
    CERR_COMPOUND_TYPE_IN_ERROR,

    CERR_SIGNALLING_NAN_CONSTANT_WAS_USED,

    CERR_CANNOT_USE_COMPINT_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_FLOAT_LIT_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_ASTCODE_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_ASTBLOCK_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_BUILTIN_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_NAMESPACE_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_SOURCEFILE_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_FOREIGN_SOURCE_TYPE_AT_RUNTIME,
    CERR_CANNOT_USE_TYPE_OF_TYPES_AT_RUNTIME,
    CERR_CANNOT_USE_STRUCTLIKE_FLAGGED_AS_COMPTIME_ONLY_AT_RUNTIME,
    CERR_CANNOT_USE_MACRO_OR_COMPTIMEPROC_AT_RUNTIME,
    CERR_CANNOT_USE_PROCLIKE_OVERLOAD_AT_RUNTIME,
    CERR_CANNOT_USE_PROCLIKE_POLYMORPH_AT_RUNTIME,
    CERR_CANNOT_USE_COMPOUND_POLYMORPH_AT_RUNTIME,
    CERR_UNKNOWN_WHEN_EXPECTED_KNOWN_CONSTANT,
    CERR_EXPECTED_TYPE_OR_PROCLIKE,
    CERR_CANNOT_USE_SINK_AS_LHV_OF_OP_AND_ASSIGN_STATEMENT,
    CERR_UNKOWN_MEMBER_IN_STRUCT,

    CERR_CAST_REQUIRES_ONE_PARAMETER,
    CERR_CAST_REQUIRES_SINGLE_PARAMETER,
    CERR_PROC_INVOC_PARAM_COUNT_MISMATCH,
    CERR_TOO_FEW_PROC_PARAMETERS,
    CERR_TOO_MANY_PROC_PARAMETERS,
    CERR_TOO_MANY_EXPR_NODES,
    CERR_TOO_MANY_VIRTUAL_NODES,
    CERR_TOO_MANY_NODES_IN_LARGE_LIST,
    CERR_TOO_FEW_RETURN_ARGUMENTS,
    CERR_TOO_MANY_RETURN_ARGUMENTS,
    CERR_TOO_FEW_LHV,
    CERR_TOO_MANY_LHV,
    CERR_TYPE_AND_VALUE_COUNT_DIFFER_IN_VAR_DECL,
    CERR_CANNOT_USE_REGULAR_VAR_DECLARATION_IN_ENUMS,
    CERR_CANNOT_USE_TYPE_AND_INIT_VAR_DECL_FORM_IN_COMPOUNDS,
    CERR_SINGLE_TO_MULTI_ASSIGN_MUST_SHARE_TYPE,
    CERR_TOO_MANY_COMPOUNDS_IN_SAME_FILE,

    CERR_TRYING_TO_EVALUATE_SINK,
    CERR_RESERVED_IDENTIFIER_AS_LVALUE,
    CERR_CONSTANT_AS_LVALUE,
    CERR_TEMPORARY_AS_LVALUE,
    CERR_DEREF_STRUCTLIKE_IN_ERROR,
    CERR_DOT_DECENT_NON_REFERENCABLE_AS_LVALUE,
    CERR_PROC_PARAM_AS_LVALUE,
    CERR_GLOBAL_BINDING_ON_STATEMENT_WITH_ERROR,
    CERR_INVALID_PTRDIFF_OP,
    CERR_INVALID_CAST,
    CERR_INVALID_CAST_NYKA_AS_CONSTANT,
    CERR_INVALID_EVAL_NYKA,
    CERR_CAST_NEGATIVE_TO_UNSIGNED,
    CERR_CAST_REQUIRES_EXPLICIT,
    CERR_IMPLICIT_CONST_INT_CAST_OOB,
    CERR_DIVISION_BY_ZERO,

    CERR_SATURATING_CAST_REQUIRES_NUMERIC_OR_RAW_INTEGRAL,
    CERR_OPERATOR_REQUIRES_SIZED_OPERANDS,
    CERR_OPERATOR_REQUIRES_NUMERIC_OPERANDS,
    CERR_OPERATOR_REQUIRES_ONE_FP_OPERAND,
    CERR_OPERATOR_REQUIRES_NUMERIC_INTEGRAL_OPERANDS,
    CERR_OPERATOR_REQUIRES_RAW_OR_INTEGRAL_OPERANDS,
    CERR_OPERATOR_REQUIRES_BOOLEAN_OPERANDS,
    CERR_OPERATOR_REQUIRES_NON_NEGATIVE_SECOND_OPERAND,
    CERR_OPERATOR_REQUIRES_SMALL_SECOND_OPERAND,
    CERR_CANNOT_MIX_RAW_INTEGRAL_WITH_NON_INTEGRAL_IN_OP,
    CERR_CANNOT_MIX_POINTER_WITH_NON_INTEGRAL_IN_OP,
    CERR_NOT_A_VALID_OPERATION_ON_POINTER,
    CERR_NOT_A_VALID_OPERATION_ON_RAW_INTEGRAL,

    CERR_INDEXING_REQUIRES_NUMERIC_INDEX,
    CERR_INDEXING_REQUIRES_TOTAL_BYTES_COUNT_FITTING_IN_I64,
    CERR_INDEXING_OUT_OF_BOUNDS,
    CERR_CANNOT_RUNTIME_ITERATE_THROUGH_ARRAY_WITH_COMPTIME_ONLY,

    CERR_COMPINT_OVERFLOW,
    CERR_EXPECTED_NO_HIGHER_THAN_32_BITS,
    CERR_FILENAME_TOO_LONG,
    CERR_INVALID_FILE_LOAD_DIRECTIVE,
    CERR_INVALID_DECLARATION_IN_ENUM,

    CERR_EXPECTED_BOOLEAN,
    CERR_ADDRESSOF_EXPECTED_BOUND,
    CERR_ADDRESSOF_EXPECTED_NON_COMPINT_BOUND,
    CERR_CONST_ADDRESSOF_EXPECTED_NON_LOCAL_VAR_BOUND,
    CERR_CONTROL_FLOW_STATEMENT_MISSING_CHILD_BLOCK,
    CERR_CANNOT_COMPACT_THIS_TYPE,
    CERR_CANNOT_DO_PTRDIFF_BETWEEN_RAWPTR_AND_PTR,
    CERR_CANNOT_DO_PTRDIFF_BETWEEN_POINTERS_TO_DIFFERENT_SIZED_TYPES,
    
    CERR_CANNOT_ACCESS_PACKAGE_DECLARATION_FROM_OTHER,

    CERR_SIGNED_UNSIGNED_MISMATCH_ON_OPERATION,
    CERR_SIGNED_UNSIGNED_MISMATCH_WITHIN_ARRAY_LITERAL,
    CERR_TYPE_MISMATCH_WITHIN_NON_NUMERIC_ARRAY_LITERAL,
    CERR_TYPE_MISMATCH_FOR_OPERATION,
    CERR_OPERATION_WOULD_OVERFLOW,
    CERR_INEXACT_QUOTIENT,

    CERR_MISSING_TYPE_INFERRENCE,

    CERR_INVALID_MODULO_OP_BETWEEN_NON_RAW,
    CERR_TYPE_NOT_INDEXABLE,

    CERR_TOO_MANY_ARGUMENTS_IN_SIGNATURE,
    
    CERR_TOO_MANY_IDENTIFIERS,
    CERR_RESULTING_IDENTIFIER_TOO_LONG,
    CERR_TOO_MANY_PROC_BODIES,
    CERR_TOO_MANY_USER_TYPES,
    CERR_TOO_MANY_GLOBAL_VARIABLES,
    CERR_TOO_MANY_GLOBAL_CONSTANT_VALUES,
    CERR_TOO_MANY_LOCAL_CONSTANTS,
    CERR_TOO_MANY_INSTRUCTIONS_IN_PROC,
    CERR_TOO_MANY_EXPANSION_LEVELS,
    CERR_TOO_MANY_RUNTIME_MEMBERS_IN_STRUCT,

    CERR_ELSE_WITHOUT_IF,

    CERR_NAN_RESULT_FROM_OP_INVOLVING_NON_NAN,
    CERR_INFINITE_RESULT_FROM_OP_INVOLVING_FINITE,
    CERR_SUBNORMAL_RESULT_FROM_OP_INVOLVING_NORMAL,
    CERR_LOSING_PREC_ON_INT_TO_FP_CONVERSION,
    CERR_RAW_INTEGRAL_HAS_NO_DEFAULT_CAST_TO_FP,
    CERR_ISOLATED_DOT_DESCENT_MISSING_UPWARDS_INFERRENCE,

    CERR_COMPLEX_TYPE_DECL_FORM_OUTSIDE_CONST_DECLARATION_WITH_SINGLE_RHV,
    CERR_PROCLIKE_DECL_FORM_OUTSIDE_SIGN_OR_CONST_DECLARATION_WITH_SINGLE_RHV,
    CERR_PROCSIGN_IN_ERROR,

    CERR_TRYING_TO_DEREF_ADDRESS_0,

    //
    // Validation error codes
    BASE_OF_VALIDATION_ERRORS         = 6100,
    //

    VERR_EXPLICIT_ERROR,
    VERR_STATIC_ASSERT_FAILED,
    VERR_COMPTIME_EXEC_FAILED,
    VERR_UNALLOWED_IDENTIFIER_SHADOWING,
//    VERR_STATEMENT_AFTER_RETURN_OR_BREAK,
//    VERR_UNALLOWED_VERY_LARGE_SLOT_COUNT_ON_OUT_PARAM,

    //
    // Linker error codes
    BASE_OF_LINKER_ERRORS             = 7100,
    //

    LERR_FAILED_WRITING_TO_OUTPUT,

    LERR_UNRESOLVED_SYMBOL,

    //
    // Internal Implementation error codes
    BASE_OF_FATAL_ERRORS             = 10100,
    //

    FERR_RUNTIME_EVAL_TYPING_OF_COMPTIME,
    FERR_ASSERTION_FAILED,
    FERR_UNEXPECTED_SYNTAX,
	FERR_UNREACHABLE,

    FERR_UNKNOWN_CONSTANT_OP_CONVERTED_TO_RUNTIME,
    FERR_NOT_YET_IMPLEMENTED,
    FERR_TOO_MANY_ENTITIES,
    FERR_OTHER,

    // The end
    E_LOC_ERROR_END

};



#endif // LOCLIB_ERROR_ENUMS_H_

